os: Visual Studio 2015

## .NET Core SDK preview1 is already installed in the build worker image Visual Studio 2015
##
## To install a specific version:
##
## install:
##   # .NET Core SDK binaries
##   ## 1) from direct url  
##   - ps: $url = "https://go.microsoft.com/fwlink/?LinkID=798402" # v1.0.0-preview1 x64
##   ## 2) from url based on version, for example using an env var CLI_VERSION that can be a
##   ##    a specific version `1.0.0-preview2-003121` or `Latest` (for latest dev version)
##   - ps: $url = "https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/$($env:CLI_VERSION)/dotnet-dev-win-x64.$($env:CLI_VERSION.ToLower()).zip"
##   # Download .NET Core SDK and add to PATH
##   - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
##   - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
##   - ps: $tempFile = [System.IO.Path]::GetTempFileName()
##   - ps: (New-Object System.Net.WebClient).DownloadFile($url, $tempFile)
##   - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFile, $env:DOTNET_INSTALL_DIR)
##   - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

environment:
  matrix:
    - CLI_VERSION: 1.0.0-preview4-004233

install:
  # .NET Core SDK binaries
  - ps: $url = "https://go.microsoft.com/fwlink/?linkid=837977"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: $tempFile = [System.IO.Path]::GetTempFileName()
  - ps: (New-Object System.Net.WebClient).DownloadFile($url, $tempFile)
  - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFile, $env:DOTNET_INSTALL_DIR)
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"  
  # follow normal installation from binaries

build_script:
  # dotnet info
  - ps: dotnet --version
  - ps: dotnet --info
  # Run dotnet new 
  - ps: cd Solinor.MonthlyWageCalculation
  - ps: dotnet restore
  - ps: dotnet build
  - ps: cd ..
  - ps: cd Solinor.MonthlyWageCalculation.UnitTests
  - ps: dotnet restore
  - ps: dotnet build
  - ps: dotnet test
  - ps: cd ..
  - ps: cd Solinor.MonthlyWageCalculation.ConsoleApp
  - ps: dotnet restore
  - ps: dotnet build
  - ps: cd ..  
  - ps: cd Solinor.MonthlyWageCalculation.WebApp
  - ps: dotnet restore
  - ps: dotnet build
  - ps: cd ..  

test:
  assemblies:
    - Solinor.MonthlyWageCalculation.UnitTests.dll

test_script:
  - ps: cd Solinor.MonthlyWageCalculation.UnitTests
  - ps: dotnet test
  - ps: cd ..

version: 1.0.{build}